include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.cscs.yml'

stages:
  - allocate
  - test
  - deallocate

default:
  image: $IMAGE

allocate cuda 10:
  stage: allocate
  extends: .daint_alloc
  variables:
    PULL_IMAGE: 'YES'

.run_test_cuda_10_shared:
  extends: .daint
  stage: test
  script:
    - cd $TEST_FOLDER
    - sirius.scf $SIRIUS_FLAGS

test_01_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test01

test_02_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test02

test_03_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test03

test_04_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test04

test_05_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test05

test_06_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test06

test_07_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test07

test_08_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test08

test_09_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test09

test_10_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test10

test_11_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test11

test_12_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test12

test_13_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test13

test_14_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test14

test_15_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test15

test_16_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test16

test_17_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test17

test_18_cuda_10:
  extends: .run_test_cuda_10_shared
  variables:
    TEST_FOLDER: /sources/verification/test18

deallocate cuda 10:
  stage: deallocate
  extends: .daint_dealloc