name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y gfortran mpich libmpich-dev liblapack-dev libhdf5-dev libgsl-dev libfftw3-dev libxc-dev

      - name: Build dependencies
        run: ./ci/github_build_dependencies.sh

      - name: Build SIRIUS
        run: ./ci/github_build_sirius.sh

      - name: Run unit tests
        run: ./ci/github_run_unit_tests.sh

      - name: Run verification with ReFrame
        run: ./ci/github_run_verification.sh

  build_rocm:
    runs-on: ubuntu-latest
    container: stabbles/sirius-rocm
    steps:
      - uses: actions/checkout@v2
      - name: Setup Spack
        run: rm -rf /user_repo/spack && cp -r ${GITHUB_WORKSPACE}/spack /user_repo/
      - name: Build SIRIUS
        run: spack --color always -e ci dev-build --source-path ${GITHUB_WORKSPACE} sirius@develop %gcc@9.3.0 build_type=RelWithDebInfo +rocm ^spfft +rocm ^openblas threads=openmp ^openmpi

  build_cuda_10:
    runs-on: ubuntu-latest
    container: stabbles/sirius-cuda-10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Spack
        run: rm -rf /user_repo/spack && cp -r ${GITHUB_WORKSPACE}/spack /user_repo/
      - name: Build SIRIUS
        run: spack --color always -e ci dev-build --source-path ${GITHUB_WORKSPACE} sirius@develop %gcc@7.5.0 build_type=RelWithDebInfo +cuda ^cuda@:10 ^openblas threads=openmp ^mpich

  build_cuda_11:
    runs-on: ubuntu-latest
    container: stabbles/sirius-cuda-11
    steps:
      - uses: actions/checkout@v2
      - name: Setup Spack
        run: rm -rf /user_repo/spack && cp -r ${GITHUB_WORKSPACE}/spack /user_repo/
      - name: Build SIRIUS
        run: spack --color always -e ci dev-build --source-path ${GITHUB_WORKSPACE} sirius@develop %gcc@9.3.0 build_type=RelWithDebInfo +cuda ^cuda@:11 ^openblas threads=openmp ^mpich

  build_elpa_mpich:
    runs-on: ubuntu-latest
    container: stabbles/sirius-cpu
    steps:
      - uses: actions/checkout@v2
      - name: Setup Spack
        run: rm -rf /user_repo/spack && cp -r ${GITHUB_WORKSPACE}/spack /user_repo/
      - name: Build SIRIUS
        run: spack --color always -e ci dev-build --source-path ${GITHUB_WORKSPACE} sirius@develop %gcc@7.5.0 build_type=RelWithDebInfo +elpa ^openblas threads=openmp ^mpich

  build_elpa_openmpi:
    runs-on: ubuntu-latest
    container: stabbles/sirius-cpu
    steps:
      - uses: actions/checkout@v2
      - name: Setup Spack
        run: rm -rf /user_repo/spack && cp -r ${GITHUB_WORKSPACE}/spack /user_repo/
      - name: Build SIRIUS
        run: spack --color always -e ci dev-build --source-path ${GITHUB_WORKSPACE} sirius@develop %gcc@7.5.0 build_type=RelWithDebInfo +elpa ^openblas threads=openmp ^openmpi
